<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create("countries", function (Blueprint $table) {
            $table->id();
            $table->string("iso_code", 3);
            $table->string("name", 50);
            $table->softDeletes();
            $table->timestamps();
        });

        DB::statement("INSERT INTO music_biblio.countries (iso_code, `name`)
VALUES
    ('ALB', 'Albania'),
    ('AND', 'Andorra'),
    ('BIH', 'Bosnia y Herzegovina'),
    ('HRV', 'Croacia'),
    ('SVN', 'Eslovenia'),
    ('ESP', 'España'),
    ('GRC', 'Grecia'),
    ('ITA', 'Italia'),
    ('MKD', 'Macedonia'),
    ('MLT', 'Malta'),
    ('MNE', 'Montenegro'),
    ('PRT', 'Portugal'),
    ('SMR', 'San Marino'),
    ('VAT', 'Santa Sede'),
    ('SRB', 'Serbia'),
    ('DEU', 'Alemania'),
    ('AUT', 'Austria'),
    ('BEL', 'Bélgica'),
    ('FRA', 'Francia'),
    ('LIE', 'Liechtenstein'),
    ('LUX', 'Luxemburgo'),
    ('MCO', 'Mónaco'),
    ('NLD', 'Países Bajos'),
    ('CHE', 'Suiza'),
    ('BLR', 'Belarús'),
    ('BGR', 'Bulgaria'),
    ('HUN', 'Hungría'),
    ('MDA', 'Moldavia'),
    ('POL', 'Polonia'),
    ('CZE', 'República Checa'),
    ('SVK', 'República Eslovaca'),
    ('ROU', 'Rumanía'),
    ('RUS', 'Rusia'),
    ('UKR', 'Ucrania'),
    ('DNK', 'Dinamarca'),
    ('EST', 'Estonia'),
    ('FIN', 'Finlandia'),
    ('IRL', 'Irlanda'),
    ('ISL', 'Islandia'),
    ('LVA', 'Letonia'),
    ('LTU', 'Lituania'),
    ('NOR', 'Noruega'),
    ('GBR', 'Reino Unido'),
    ('SWE', 'Suecia'),
    ('AGO', 'Angola'),
    ('CMR', 'Camerún'),
    ('COG', 'Congo'),
    ('GAB', 'Gabón'),
    ('GNQ', 'Guinea Ecuatorial'),
    ('CAF', 'República Centroafricana'),
    ('COD', 'República Democrática del Congo'),
    ('STP', 'Santo Tomé y Príncipe'),
    ('TCD', 'Chad'),
    ('BWA', 'Botswana'),
    ('LSO', 'Lesotho'),
    ('NAM', 'Namibia'),
    ('ZAF', 'Sudáfrica'),
    ('SWZ', 'Swazilandia'),
    ('BEN', 'Benin'),
    ('BFA', 'Burkina Faso'),
    ('CPV', 'Cabo Verde'),
    ('CIV', 'Costa de Marfil'),
    ('GMB', 'Gambia'),
    ('GHA', 'Ghana'),
    ('GIN', 'Guinea'),
    ('GNB', 'Guinea-Bissau'),
    ('LBR', 'Liberia'),
    ('MLI', 'Mali'),
    ('MRT', 'Mauritania'),
    ('NER', 'Níger'),
    ('NGA', 'Nigeria'),
    ('SEN', 'Senegal'),
    ('SLE', 'Sierra Leona'),
    ('TGO', 'Togo'),
    ('BDI', 'Burundi'),
    ('COM', 'Comores'),
    ('DJI', 'Djibouti'),
    ('ERI', 'Eritrea'),
    ('ETH', 'Etiopía'),
    ('KEN', 'Kenia'),
    ('MDG', 'Madagascar'),
    ('MWI', 'Malawi'),
    ('MUS', 'Mauricio'),
    ('MOZ', 'Mozambique'),
    ('RWA', 'Ruanda'),
    ('SYC', 'Seychelles'),
    ('SOM', 'Somalia'),
    ('TZA', 'Tanzania'),
    ('UGA', 'Uganda'),
    ('ZMB', 'Zambia'),
    ('ZWE', 'Zimbabwe'),
    ('DZA', 'Argelia'),
    ('EGY', 'Egipto'),
    ('LBY', 'Libia'),
    ('MAR', 'Marruecos'),
    ('ESH', 'Sáhara Occidental'),
    ('SSD', 'Sudán del Sur'),
    ('SDN', 'Sudán'),
    ('TUN', 'Túnez'),
    ('BLZ', 'Belice'),
    ('CRI', 'Costa Rica'),
    ('SLV', 'El Salvador'),
    ('GTM', 'Guatemala'),
    ('HND', 'Honduras'),
    ('MEX', 'México'),
    ('NIC', 'Nicaragua'),
    ('PAN', 'Panamá'),
    ('CAN', 'Canadá'),
    ('USA', 'Estados Unidos de América'),
    ('ARG', 'Argentina'),
    ('BOL', 'Bolivia'),
    ('BRA', 'Brasil'),
    ('COL', 'Colombia'),
    ('ECU', 'Ecuador'),
    ('GUY', 'Guyana'),
    ('PRY', 'Paraguay'),
    ('PER', 'Perú'),
    ('SUR', 'Surinam'),
    ('URY', 'Uruguay'),
    ('VEN', 'Venezuela'),
    ('CHL', 'Chile'),
    ('ATG', 'Antigua y Barbuda'),
    ('BHS', 'Bahamas'),
    ('BRB', 'Barbados'),
    ('CUB', 'Cuba'),
    ('DMA', 'Dominica'),
    ('GRD', 'Granada'),
    ('HTI', 'Haití'),
    ('JAM', 'Jamaica'),
    ('DOM', 'República Dominicana'),
    ('KNA', 'San Cristóbal y Nieves'),
    ('LCA', 'Santa Lucía'),
    ('VCT', 'San Vicente y las Granadinas'),
    ('TTO', 'Trinidad y Tobago'),
    ('KAZ', 'Kazajstán'),
    ('KGZ', 'Kirguistán'),
    ('TJK', 'Tadyikistán'),
    ('TKM', 'Turkmenistán'),
    ('UZB', 'Uzbekistán'),
    ('AFG', 'Afganistán'),
    ('BGD', 'Bangladesh'),
    ('BTN', 'Bhután'),
    ('IND', 'India'),
    ('IRN', 'Irán'),
    ('MDV', 'Maldivas'),
    ('NPL', 'Nepal'),
    ('PAK', 'Pakistán'),
    ('LKA', 'Sri Lanka'),
    ('SAU', 'Arabia Saudí'),
    ('ARM', 'Armenia'),
    ('AZE', 'Azerbaiyán'),
    ('BHR', 'Bahréin'),
    ('ARE', 'Emiratos Árabes Unidos'),
    ('GEO', 'Georgia'),
    ('YEM', 'Yemen'),
    ('IRQ', 'Iraq'),
    ('ISR', 'Israel'),
    ('JOR', 'Jordania'),
    ('KWT', 'Kuwait'),
    ('LBN', 'Líbano'),
    ('OMN', 'Omán'),
    ('QAT', 'Qatar'),
    ('SYR', 'Siria'),
    ('PSE', 'Palestina'),
    ('TUR', 'Turquía'),
    ('CYP', 'Chipre'),
    ('PRK', 'Corea del Norte'),
    ('KOR', 'Corea del Sur'),
    ('JPN', 'Japón'),
    ('MNG', 'Mongolia'),
    ('TWN', 'Taiwán, China'),
    ('CHN', 'China'),
    ('BRN', 'Brunei'),
    ('KHM', 'Camboya'),
    ('PHL', 'Filipinas'),
    ('IDN', 'Indonesia'),
    ('LAO', 'Laos'),
    ('MYS', 'Malasia'),
    ('MMR', 'Myanmar'),
    ('SGP', 'Singapur'),
    ('THA', 'Tailandia'),
    ('TLS', 'Timor Oriental'),
    ('VNM', 'Vietnam'),
    ('AUS', 'Australia'),
    ('NZL', 'Nueva Zelanda'),
    ('FJI', 'Fiji'),
    ('SLB', 'Islas Salomón'),
    ('PNG', 'Papúa Nueva Guinea'),
    ('VUT', 'Vanuatu'),
    ('MHL', 'Islas Marshall'),
    ('KIR', 'Kiribati'),
    ('FSM', 'Micronesia'),
    ('NRU', 'Nauru'),
    ('PLW', 'Palaos'),
    ('WSM', 'Samoa'),
    ('TON', 'Tonga'),
    ('TUV', 'Tuvalu');");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
